-- MIDE: persistent, per-kind idempotency for the e-mail notifications sent by
-- POST /api/mide/event (Ensayo 2).
--
-- NOTE: this is the form of the migration that was APPLIED MANUALLY to the
-- live Supabase project. Its single-timestamp claim (alert_notified_at /
-- recovery_notified_at used both as "claimed" and "sent") is superseded by
-- 20260905120003_mide_event_notification_lease.sql, which upgrades this live
-- schema to a two-phase claim/confirm with a lease so a crash between "I'll
-- send it" and "it was sent" is recoverable. Do NOT edit this file to match
-- 003 — it must keep describing what actually ran here.
--
-- Before: /api/mide/event only ever persisted the episode row. No e-mail was
-- ever sent, and events.notified_at (a single nullable timestamp from the
-- original schema) was never written.
--
-- After: the route sends TWO independent e-mails over the life of one episode
-- row -- an ALERT e-mail on the alarm-engine open, and a RECOVERY e-mail on
-- the close/recover POST. Each must be sent at most once, even when the
-- firmware retries the same POST (it retries the open and the close with the
-- SAME eventId until it gets a 200). One timestamp is not enough to tell
-- "alert already sent" from "recovery already sent", so this migration adds
-- one column per kind and an atomic claim function.
--
--   * events.alert_notified_at    -- set when the ALERT e-mail is sent
--   * events.recovery_notified_at -- set when the RECOVERY e-mail is sent
--   * mide_claim_event_notification(id, kind) -> boolean
--        atomically "claims" a kind: UPDATE ... WHERE <kind>_notified_at IS
--        NULL. Returns true only to the ONE caller that flipped it from NULL,
--        so concurrent retries collapse to a single send. The decision is
--        persisted in the DB, so it also survives a server restart.
--   * mide_release_event_notification(id, kind) -> void
--        best-effort rollback: clears the timestamp again so a later retry can
--        re-attempt, used when the e-mail provider call fails.
--
-- mide_upsert_event also grows its RETURN shape: it now hands back the row id
-- (needed to claim a notification) plus the stored value/peak/started_at/
-- ended_at, so the route can build the e-mail body without a second SELECT.
-- Its argument list is UNCHANGED, so the route's rpc() call site only needs to
-- read the new columns.
--
-- The original events.notified_at column is left untouched (still unused);
-- removing it is out of scope here.
--
-- IMPORTANT: apply MANUALLY to the live Supabase project after diffing
-- against the real schema (see 20260818000000_mide_schema.sql header). This
-- migration is idempotent / safe to re-run.

-- ---------------------------------------------------------------------------
-- 1. Per-kind notification timestamps.
-- ---------------------------------------------------------------------------

alter table public.events
  add column if not exists alert_notified_at timestamptz;

alter table public.events
  add column if not exists recovery_notified_at timestamptz;

comment on column public.events.alert_notified_at is
  'Set by /api/mide/event when the ALERT e-mail for this episode has been '
  'handed to the e-mail provider. NULL = not yet notified. Claimed atomically '
  'via mide_claim_event_notification so firmware retries never double-send.';

comment on column public.events.recovery_notified_at is
  'Set by /api/mide/event when the RECOVERY e-mail for this episode has been '
  'handed to the e-mail provider. NULL = not yet notified.';

-- ---------------------------------------------------------------------------
-- 2. mide_upsert_event: same arguments, richer RETURN.
--    RETURNS TABLE shape changes, so the old function must be dropped first
--    (CREATE OR REPLACE cannot change OUT parameters).
-- ---------------------------------------------------------------------------

drop function if exists public.mide_upsert_event(
  uuid, text, text, text, timestamptz, numeric, timestamptz, numeric, jsonb
);

create function public.mide_upsert_event(
  p_device_id  uuid,
  p_event_uid  text,
  p_type       text,
  p_severity   text,
  p_started_at timestamptz,
  p_value      numeric,
  p_ended_at   timestamptz,
  p_peak_value numeric,
  p_metadata   jsonb
)
returns table (
  was_inserted boolean,
  event_status text,
  event_id     uuid,
  event_value  numeric,
  event_peak   numeric,
  event_started_at timestamptz,
  event_ended_at   timestamptz
)
language plpgsql
set search_path = public
as $$
begin
  return query
  insert into public.events as e (
    device_id, event_uid, event_type, severity,
    started_at, value_at_start, ended_at, peak_value, status, metadata
  )
  values (
    p_device_id, p_event_uid, p_type, p_severity,
    p_started_at, p_value, p_ended_at, p_peak_value,
    case when p_ended_at is not null then 'resolved' else 'open' end,
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (device_id, event_uid) do update set
    ended_at   = coalesce(excluded.ended_at, e.ended_at),
    peak_value = coalesce(excluded.peak_value, e.peak_value),
    severity   = excluded.severity,
    status     = case when excluded.ended_at is not null then 'resolved' else e.status end,
    metadata   = coalesce(e.metadata, '{}'::jsonb) || coalesce(excluded.metadata, '{}'::jsonb)
  -- xmax = 0 on a freshly INSERTed row, non-zero on a row updated by the
  -- ON CONFLICT path. Cast via text to avoid "operator does not exist:
  -- xid = integer" on stricter PostgreSQL builds.
  returning
    (e.xmax::text::bigint = 0),
    e.status,
    e.id,
    e.value_at_start,
    e.peak_value,
    e.started_at,
    e.ended_at;
end;
$$;

revoke all on function public.mide_upsert_event(uuid, text, text, text, timestamptz, numeric, timestamptz, numeric, jsonb) from public;
grant execute on function public.mide_upsert_event(uuid, text, text, text, timestamptz, numeric, timestamptz, numeric, jsonb) to service_role;

-- ---------------------------------------------------------------------------
-- 3. Atomic per-kind claim / release.
--    SECURITY INVOKER (default): runs as the caller (service_role).
-- ---------------------------------------------------------------------------

create or replace function public.mide_claim_event_notification(
  p_event_id uuid,
  p_kind     text
)
returns boolean
language plpgsql
set search_path = public
as $$
begin
  if p_kind = 'alert' then
    update public.events
      set alert_notified_at = now()
      where id = p_event_id and alert_notified_at is null;
  elsif p_kind = 'recovery' then
    update public.events
      set recovery_notified_at = now()
      where id = p_event_id and recovery_notified_at is null;
  else
    raise exception 'mide_claim_event_notification: kind invalido %', p_kind;
  end if;

  -- FOUND is true iff the UPDATE above matched a row, i.e. this call is the
  -- one that flipped the timestamp from NULL. Every concurrent retry gets
  -- false and must NOT send.
  return found;
end;
$$;

create or replace function public.mide_release_event_notification(
  p_event_id uuid,
  p_kind     text
)
returns void
language plpgsql
set search_path = public
as $$
begin
  if p_kind = 'alert' then
    update public.events set alert_notified_at = null where id = p_event_id;
  elsif p_kind = 'recovery' then
    update public.events set recovery_notified_at = null where id = p_event_id;
  else
    raise exception 'mide_release_event_notification: kind invalido %', p_kind;
  end if;
end;
$$;

revoke all on function public.mide_claim_event_notification(uuid, text) from public;
grant execute on function public.mide_claim_event_notification(uuid, text) to service_role;

revoke all on function public.mide_release_event_notification(uuid, text) from public;
grant execute on function public.mide_release_event_notification(uuid, text) to service_role;

-- service_role already has update, select on public.events (granted by
-- 20260905120001); the claim/release functions need nothing more.
